Some issues with navigationController
MathieuChe/TodoList_14 pull request #2
Opened 2020-12-24 09:13 UTC by MathieuChe

Item Bar Button appear on the iPhone8 Simulator but not on the other ones

2020-12-26 15:41 UTC, CoachThys requested changes
Ça tourne bien sur iPhone 11 et iPhone 12 mini en Xcode 12.3 et iOS 14.3.

Au niveau du layout, tu peux faire des efforts sur la présentation des items de ta todoList ne serait-ce que pour les faire respirer.

Sinon ça tourne bien, l'écrite des données en plist pour conserver les données d'une session à l'autre 👍

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +        navigationController?.navigationBar.barTintColor = .init(red: 0.8, green: 0.5, blue: 0.5, alpha: 0.6)
Les couleurs dans une app sont souvent réutilisées, on peut donc les ranger dans la struct Constants

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +            try data.write(to: dataFilePath!)
"!" est quasi interdit. On appelle ça le force unwrapping, cause majeure de crashs. Il faut unwrapper proprement le chemin du fichier, débarasse toi de l'optionnel avec un guard let par exemple.

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +        if let data = try? Data(contentsOf: dataFilePath!){
Le chemin du fichier ne doit pas être optionnel. De manière générale si tu suis des cours où vois des morceaux de codes où il y a une déclaration explicite ou un unwrapping explicite tu dois t'inquiéter.

```
// Déclaration explicite
let myString: String!
```

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +        if let data = try? Data(contentsOf: dataFilePath!){
C'est toléré uniquement pour les IBOutlets, car on est sûr qu'ils sont initialisés dans le awake from nib et donc avant qu'on y touche

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +        tableView.deselectRow(at: indexPath, animated: true)
Plutôt que s'ennuyer à désélectionner la cellule, il faut utiliser la propriété de la cellule selectionStyle. Un des états correspond à ce que tu recherches (en supposant que ce qui te stress est de voir la cellule d'une couleur différente quand tu tapes dessus)

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +        itemArray[indexPath.row].done = !itemArray[indexPath.row].done
Ça me rappelle un tuto 😜

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +        return itemArray.count
items* convention pluriel pour les listes

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +        cell.accessoryType = item.done ? .checkmark : .none
C'est ça, en plus simple, si la condition est vrai, la première partie est assigné, sinon la seconde.

cell.accessoryType = item.done ? premierePartie : secondePartie

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +            if (textField.text == nil || textField.text == "") {
Utilise la propriété isEmpty directement pour couvrir les cas qui t'intéresse

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +                let alertEmpty: UIAlertController = UIAlertController(title: "Error", message: "You should write something or cancel", preferredStyle: .alert)
emptyTextAlertController => toujours finir par le type

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +                let alertEmpty: UIAlertController = UIAlertController(title: "Error", message: "You should write something or cancel", preferredStyle: .alert)
Le titre "Error" n'est pas assez précis, quel est le type d'erreur ?

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +                self.present(alertEmpty, animated: true, completion: nil)
En terme d'UX je trouve pas ça ouf de quitter une AlertController pour en présenter une autre pour finalement revenir à la première. Il doit y avoir de meilleurs moyen de faire comprendre à l'utilisateur qu'il doit y avoir au moins un caractère pour ajouter un item

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +                let newItem: Items = Items(title: textField.text!, done: false)
Unwrapping explicite ⛔️

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Controllers/TodoListViewController.swift
> +                self.present(alertEmpty, animated: true, completion: nil)
https://stackoverflow.com/questions/37206638/disable-button-in-uialertview-while-text-field-is-empty

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Data Model/Items.swift
> +    var done: Bool = false
Pourquoi donner des valeurs par défaut alors qu'elle sont assignées à l'init ?

2020-12-26 15:41 UTC, CoachThys commented on TodoList_14/Data Model/Items.swift
> +class Items: Codable {
Soit plus précis que "Items" pour désigner tes données, qu'est-ce que c'est comme donnée ? TodoListItem ?

À quoi sert le pluriel dans le nom ? C'est une classe et non une liste

2020-12-27 16:48 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +    private var forKeyString: String = "TodoListDictionary"
Ouais c'était pour le UserDefaults mais je l'ai changé pour le NSCoder et la je vais passer a CoreData donc c'est pour cela qu'il y a des éléments que j'ai déclaré et utilisé auparavant que je n'utilise plus du tout.

2020-12-27 16:51 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +    let dataFilePath = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first?.appendingPathComponent("Items.plist")
D'accord
Constants.FileManager.itemsFilePath

2020-12-27 16:52 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +        setUpNavigationDisplay()
Alright je modifie

2020-12-27 16:56 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +        navigationController?.navigationBar.barTintColor = .init(red: 0.8, green: 0.5, blue: 0.5, alpha: 0.6)
D'accord 

navigationController?.navigationBar.barTintColor = Constants.FileManager.itemsColorNavBar

2020-12-27 17:00 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +            try data.write(to: dataFilePath!)
Ouais, dans la formation elle nous a dit qu'on le force même si ce n'est pas une bonne pratique car on est sûrs qu'il ne sera pas nil

// Use guard let to avoid forcing unwrapping
guard let dataFilePathGuard = dataFilePath else {return}
            
// Now we have to write (add) data in our dataFilePath and it's also a throw' method
try data.write(to: dataFilePathGuard)

2020-12-27 17:06 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +        if let data = try? Data(contentsOf: dataFilePath!){
Ouais dans son cours elle présente un unwrapping explicite

Du coup en mettant le dataFilePath dans un guard let c'est bon ou je dois également faire en sorte que le try ne soit pas optionnel ?

guard let dataFilePathGuard = dataFilePath else {return}

if let data = try? Data(contentsOf: dataFilePathGuard){}

2020-12-27 17:08 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +        tableView.deselectRow(at: indexPath, animated: true)
Ouais mais là le but est d'avoir une cellule qui est grisée et se dégrise via une animation et non empêcher la cellule d'être sélectionnée. Du coup c'est la méthode à utiliser ?

2020-12-27 17:08 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +        itemArray[indexPath.row].done = !itemArray[indexPath.row].done
Mdr mais je ne m'en souvenais plus du tout. Ca supprime pas mal de lignes de code

2020-12-27 17:10 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +        return itemArray.count
return itemsArray.count

2020-12-27 17:11 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +        cell.accessoryType = item.done ? .checkmark : .none
Ouais les conditions ternaires identiques à tous les langages de programmation qui les utilisent

2020-12-27 17:23 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +            if (textField.text == nil || textField.text == "") {
Ah merci. Ouais c'est plus concis et verbose à la fois

if (textField.text?.isEmpty ?? true) {}

2020-12-27 17:24 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +                let alertEmpty: UIAlertController = UIAlertController(title: "Error", message: "You should write something or cancel", preferredStyle: .alert)
Yes sir

2020-12-27 17:25 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +                let alertEmpty: UIAlertController = UIAlertController(title: "Error", message: "You should write something or cancel", preferredStyle: .alert)
"Error Empty Field"

2020-12-27 17:36 UTC, MathieuChe commented on TodoList_14/Controllers/TodoListViewController.swift
> +                let newItem: Items = Items(title: textField.text!, done: false)
Cette ligne de code n'existe plus mais je comprends la logique maintenant

2020-12-27 17:38 UTC, MathieuChe commented on TodoList_14/Data Model/Items.swift
> +    var done: Bool = false
Ce fichier n'existe plus également car je vais passer par core data et donc dans le DataModel, je vais set le Codegen à Class. Mais c'est vrai que lorsque je voulais créer des instances, je me disais c'est con car j'ai assigné des valeurs par défaut, tandis que lors de l'instanciation je devais assigner des valeurs.

2020-12-27 17:40 UTC, MathieuChe commented on TodoList_14/Data Model/Items.swift
> +class Items: Codable {
Je n'ai pas réellement réfléchi à l'appellation de cette class, j'ai suivi le nom de classe qu'elle suggérait dans son cours.

2020-12-31 13:21 UTC, merged